import java.sql.Array;

public class Problem2 {
	
	/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	 * By starting with 1 and 2, the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	 * find the sum of the even-valued terms.*/
	
	static int x=100;
	static int aArray[] = new int[x];
	
	public static int funA(){
		int i=0;
		int s=0;
		while(s<4000000) {
			if(i<=1) {aArray[i]=1;}
			else {aArray[i] = aArray[i-1]+aArray[i-2];}
			s=aArray[i];
			i++;
		}
		return i;
	}
	
	
	public static void main(String[] args) {
		int sum=0;
		for(int i = 0; i<funA(); i++) {
			if(aArray[i]%2==0) sum+=aArray[i];
		}
		
		System.out.println("Answer: " + sum);
		
	}

}
